import {drawPoint} from "./draw.js";

export const addRequestElement = (requestText, requestStatus, contextDraw, mainJsonData) => {
    const requestsDiv = document.getElementById('requests')
    const div = document.createElement('div')
    div.setAttribute('id', `${"request№"+window.amountOfRequests}`)
    div.setAttribute('onClick', `handleClickShow(${window.amountOfRequests})`)
    div.classList.add('request', 'shownRequest')
    const divData = document.createElement('div')
    divData.setAttribute('class', 'divRequestContent')
    if (requestStatus === 200){
        const jsonData = JSON.parse(requestText)
        mainJsonData.unshift(jsonData)
        drawPoint(jsonData.x, jsonData.y, jsonData.isIn, contextDraw)
        div.classList.add(`${jsonData.isIn ? 'greenStyle' : 'redStyle'}`)
        const table = document.createElement('table')
        const tr = document.createElement('tr')
        const td1 = document.createElement('td')
        const td2 = document.createElement('td')
        const td3 = document.createElement('td')
        const td4 = document.createElement('td')
        const td5 = document.createElement('td')
        td1.insertAdjacentText('beforeend', '№')
        td2.insertAdjacentText('beforeend', '(x,y,r)')
        td3.insertAdjacentText('beforeend', 'answer')
        td4.insertAdjacentText('beforeend', 'time')
        td5.insertAdjacentText('beforeend', 'execution period (ms)')
        tr.insertAdjacentElement('beforeend', td1)
        tr.insertAdjacentElement('beforeend', td2)
        tr.insertAdjacentElement('beforeend', td3)
        tr.insertAdjacentElement('beforeend', td4)
        tr.insertAdjacentElement('beforeend', td5)
        const tr2 = document.createElement('tr')
        const td12 = document.createElement('td')
        const td22 = document.createElement('td')
        const td32 = document.createElement('td')
        const td42 = document.createElement('td')
        const td52 = document.createElement('td')
        tr2.insertAdjacentElement('beforeend', td12)
        tr2.insertAdjacentElement('beforeend', td22)
        tr2.insertAdjacentElement('beforeend', td32)
        tr2.insertAdjacentElement('beforeend', td42)
        tr2.insertAdjacentElement('beforeend', td52)
        td12.insertAdjacentText('beforeend', `${window.amountOfRequests}`)
        td22.insertAdjacentText('beforeend', `(${jsonData.x},${jsonData.y},${jsonData.r})`)
        td32.insertAdjacentText('beforeend', `${jsonData.isIn ? 'hit' : 'no hit'}`)
        td42.insertAdjacentText('beforeend', `${jsonData.date}`)
        td52.insertAdjacentText('beforeend', `${jsonData.time}`)
        table.insertAdjacentElement('beforeend', tr)
        table.insertAdjacentElement('beforeend', tr2)
        divData.insertAdjacentElement('beforeend', table)

        //return `<div ><div class="divRequestContent"><table> <tr><td>№</td><td>(x,y,r)</td><td>answer</td><td>time</td><td>execution period</td></tr><tr><td>${window.amountOfRequests}</td><td>(${jsonDataFromPhp.x},${jsonDataFromPhp.y},${jsonDataFromPhp.r})</td><td>${jsonDataFromPhp.isIn ? 'hit' : 'no hit'}</td><td>${jsonDataFromPhp.date}</td><td>${jsonDataFromPhp.time}</td></tr></table></div><div class="hide" onclick="handleClickHide()">abc</div></div>`
    }
    else{
        div.classList.add('redStyle')
        const message = document.createElement('h2')
        message.classList.add('errorRequestMessage')
        message.insertAdjacentText('beforeend', 'Failed to handle this request(')
        divData.insertAdjacentElement('beforeend', message)
    }
    const divHide = document.createElement('div')
    divHide.setAttribute('class', 'hide')
    divHide.setAttribute('onclick', 'handleClickHide()')
    divHide.insertAdjacentText('beforeend', 'hide')
    div.insertAdjacentElement('beforeend', divData)
    div.insertAdjacentElement('beforeend', divHide)
    requestsDiv.insertAdjacentElement('afterbegin', div)
}

export const addRequestElementForJSON = (jsonData, num) =>{
    const requestsDiv = document.getElementById('requests')
    const div = document.createElement('div')
    div.setAttribute('id', `${"request№"+num}`)
    div.setAttribute('onClick', `handleClickShow(${num})`)
    div.classList.add('request', 'shownRequest')
    const divData = document.createElement('div')
    divData.setAttribute('class', 'divRequestContent')
    div.classList.add(`${jsonData.isIn ? 'greenStyle' : 'redStyle'}`)
    const table = document.createElement('table')
    const tr = document.createElement('tr')
    const td1 = document.createElement('td')
    const td2 = document.createElement('td')
    const td3 = document.createElement('td')
    const td4 = document.createElement('td')
    const td5 = document.createElement('td')
    td1.insertAdjacentText('beforeend', '№')
    td2.insertAdjacentText('beforeend', '(x,y,r)')
    td3.insertAdjacentText('beforeend', 'answer')
    td4.insertAdjacentText('beforeend', 'time')
    td5.insertAdjacentText('beforeend', 'execution period (ms)')
    tr.insertAdjacentElement('beforeend', td1)
    tr.insertAdjacentElement('beforeend', td2)
    tr.insertAdjacentElement('beforeend', td3)
    tr.insertAdjacentElement('beforeend', td4)
    tr.insertAdjacentElement('beforeend', td5)
    const tr2 = document.createElement('tr')
    const td12 = document.createElement('td')
    const td22 = document.createElement('td')
    const td32 = document.createElement('td')
    const td42 = document.createElement('td')
    const td52 = document.createElement('td')
    tr2.insertAdjacentElement('beforeend', td12)
    tr2.insertAdjacentElement('beforeend', td22)
    tr2.insertAdjacentElement('beforeend', td32)
    tr2.insertAdjacentElement('beforeend', td42)
    tr2.insertAdjacentElement('beforeend', td52)
    td12.insertAdjacentText('beforeend', `${num}`)
    td22.insertAdjacentText('beforeend', `(${jsonData.x},${jsonData.y},${jsonData.r})`)
    td32.insertAdjacentText('beforeend', `${jsonData.isIn ? 'hit' : 'no hit'}`)
    td42.insertAdjacentText('beforeend', `${jsonData.date}`)
    td52.insertAdjacentText('beforeend', `${jsonData.time}`)
    table.insertAdjacentElement('beforeend', tr)
    table.insertAdjacentElement('beforeend', tr2)
    divData.insertAdjacentElement('beforeend', table)
    const divHide = document.createElement('div')
    divHide.setAttribute('class', 'hide')
    divHide.setAttribute('onclick', 'handleClickHide()')
    divHide.insertAdjacentText('beforeend', 'hide')
    div.insertAdjacentElement('beforeend', divData)
    div.insertAdjacentElement('beforeend', divHide)
    requestsDiv.insertAdjacentElement('afterbegin', div)
}